name: m7_livelyness_detection
description: A single function package to detect weather the face visible in the camera is a live face or not.
version: 0.0.4+5
homepage: https://github.com/Meet-7-dating/m7_livelyness_detection
repository: https://github.com/Meet-7-dating/m7_livelyness_detection/
issue_tracker: https://github.com/Meet-7-dating/m7_livelyness_detection/issues

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  animate_do: ^3.3.1
  auto_size_text: ^3.0.0
  camera: ^0.10.5+5
  camerawesome: ^2.0.0+1
  collection:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.8.0
  image: ^4.1.3
  lottie: ^2.7.0
  plugin_platform_interface: ^2.1.6
  rxdart: ^0.27.7
  circular_progress_stack:
  uuid: ^4.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  intl_utils: ^2.8.5

flutter:
  plugin:
    platforms:
      android:
        package: com.example.m7_livelyness_detection
        pluginClass: M7LivelynessDetectionPlugin
      ios:
        pluginClass: M7LivelynessDetectionPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/m7_livelyness_detection/src/assets/lottie/livelyness-start.json
    - packages/m7_livelyness_detection/src/assets/lottie/livelyness-success.json
    - packages/m7_livelyness_detection/src/assets/lottie/step_completed.json
    - packages/m7_livelyness_detection/src/assets/final-mesh.png
    - packages/m7_livelyness_detection/src/assets/lottie/blink.json
    - packages/m7_livelyness_detection/src/assets/lottie/smile.json
    - packages/m7_livelyness_detection/src/assets/lottie/turn-left.json
    - packages/m7_livelyness_detection/src/assets/lottie/turn-right.json
    - packages/m7_livelyness_detection/src/assets/face_example.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat_regular.ttf
          weight: 400
        - asset: fonts/montserrat_medium.ttf
          weight: 500
        - asset: fonts/montserrat_semibold.ttf
          weight: 600
        - asset: fonts/montserrat_bold.ttf
          weight: 700
    - family: MontserratMedium
      fonts:
        - asset: fonts/montserrat_medium.ttf
    - family: MontserratSemibold
      fonts:
        - asset: fonts/montserrat_semibold.ttf

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: LangLivelyness # Optional. Sets the name for the generated localization class. Default: S
  main_locale: es
